name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      name: Test on ${{ matrix.platform.os }} using Xcode ${{ matrix.xcode }}
      runs-on: macos-13
      
      env:
          xcodeproj: PlistDesign.xcodeproj
          
      strategy:
        matrix:
          platform:
            - { os: iOS, scheme: PlistDesign }
          xcode:
            - '15.0.1'
            
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Set up environment
          uses: ./.github/actions/setup
          with:
            xcode: ${{ matrix.xcode }}
                  
        - name: Run tests
          uses: ./.github/actions/test
          with:
            xcode: ${{ matrix.xcode }}
            scheme: ${{ matrix.platform.scheme }}
            platform: ${{ matrix.platform.os }}
            
    swiftlint:
      name: Lint code with SwiftLint
      runs-on: macos-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Run SwiftLint
          run: swiftlint lint --reporter github-actions-logging
